plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version "${loom_version}" apply(false)
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.49-beta' apply(false)
}

version = mod_version

allprojects {
    apply plugin: "idea"

    tasks.withType(Javadoc).configureEach {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.encoding = 'UTF-8'
    }
}

subprojects {
    version = mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }

        // Balm
        maven {
            url "https://maven.twelveiterations.com/repository/maven-public/"
            content {
                includeGroup "net.blay09.mods"
            }
        }
        // Create + friends
        maven { url "https://maven.createmod.net" }              // Create
        maven { url "https://mvn.devos.one/snapshots/" }         // Create Fabric
        maven { url "https://mvn.devos.one/releases/" }          // Porting Lib
        maven { url "https://maven.tterrag.com/" }               // Flywheel / Registrate
        maven { url "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
        maven { url "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // Forge Config API Port
        maven {
            name = 'BlameJared'
            url = 'https://maven.blamejared.com'
        }
        maven { url "https://cursemaven.com" }
        maven { url "https://maven.ryanhcode.dev/releases" } // Sable, Aero
        maven { url "https://maven.theillusivec4.top/" } // Curios
    }

    plugins.withType(JavaPlugin) {
        dependencies {
            implementation "com.google.code.gson:gson:${gson_version}"
            implementation "org.antlr:antlr4-runtime:${antlr_version}"
            implementation "org.xerial:sqlite-jdbc:${sqlite_version}"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
    }
}
